// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // migrate / db push / seed need a session (or direct) connection — the
    // transaction pooler can't run migrations. Prefer DIRECT_URL (session
    // pooler, port 5432) and fall back to DATABASE_URL for local setups.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
